name: RuboCop

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres env:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.0.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-rubocop-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-rubocop-
    - name: Install gems
      run: bundle install --jobs 4 --retry 3
    - name: Precompile Assets
      run : bundle exec rails assets:precompile
    - name: Setup database
      run: cp ./config/example.database.yml ./config/database.yml && bundle exec rails db:create
    - name: Run RuboCop
      run: bundle exec rubocop --parallel
    - name: Run Rspec
      run: bundle exec rspec
